export const IS_PROD = process.env.NODE_ENV === "production";

export const REACT_APP_FIREBASE_API_KEY = IS_PROD
  ? process.env.REACT_APP_FIREBASE_API_KEY_PROD
  : process.env.REACT_APP_FIREBASE_API_KEY_DEV;

export const REACT_APP_FIREBASE_AUTH_DOMAIN = IS_PROD
  ? process.env.REACT_APP_FIREBASE_AUTH_DOMAIN_PROD
  : process.env.REACT_APP_FIREBASE_AUTH_DOMAIN_DEV;

export const REACT_APP_FIREBASE_DATABASE_URL = IS_PROD
  ? process.env.REACT_APP_FIREBASE_DATABASE_URL_PROD
  : process.env.REACT_APP_FIREBASE_DATABASE_URL_DEV;

export const REACT_APP_FIREBASE_PROJECT_ID = IS_PROD
  ? process.env.REACT_APP_FIREBASE_PROJECT_ID_PROD
  : process.env.REACT_APP_FIREBASE_PROJECT_ID_DEV;

export const REACT_APP_FIREBASE_STORAGE_BUCKET = IS_PROD
  ? process.env.REACT_APP_FIREBASE_STORAGE_BUCKET_PROD
  : process.env.REACT_APP_FIREBASE_STORAGE_BUCKET_DEV;

export const REACT_APP_FIREBASE_MESSAGING_SENDER_ID = IS_PROD
  ? process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID_PROD
  : process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID_DEV;

export const REACT_APP_FIREBASE_APP_ID = IS_PROD
  ? process.env.REACT_APP_FIREBASE_APP_ID_PROD
  : process.env.REACT_APP_FIREBASE_APP_ID_DEV;

export const REACT_APP_FIREBASE_MEASUREMENT_ID = IS_PROD
  ? process.env.REACT_APP_FIREBASE_MEASUREMENT_ID_PROD
  : process.env.REACT_APP_FIREBASE_MEASUREMENT_ID_DEV;

export const REACT_APP_VERCEL_CLIENT_ID = IS_PROD
  ? process.env.REACT_APP_VERCEL_CLIENT_ID_PROD
  : process.env.REACT_APP_VERCEL_CLIENT_ID_DEV;

export const REACT_APP_VERCEL_CLIENT_SECRET = IS_PROD
  ? process.env.REACT_APP_VERCEL_CLIENT_SECRET_PROD
  : process.env.REACT_APP_VERCEL_CLIENT_SECRET_DEV;
